In [2]:
import numpy as np

$$
\text{cond}A=||A||\cdot||A^{-1}||
$$

In [3]:
def cond(A, norm):
    return norm(A) * norm(np.linalg.inv(A))

# 1

In [11]:
A = np.array([
	[10, 7, 8, 7],
	[7, 5, 6, 5],
	[8, 6, 10, 9],
	[7, 5, 9, 10],
])

B = np.array([
    32, 23, 33, 31
])

Ap = np.array([
	[10, 7, 8.1, 7.2],
	[7.08, 5.04, 6, 5],
	[8, 5.98, 9.89, 9],
	[6.99, 4.99, 9, 9.98],
])

Bp = np.array([
    32.1, 22.9, 33.1, 30.9
])

sol = np.linalg.solve(A, B)
print(sol)

def solve(Ae, Be):
    curr_sol = np.linalg.solve(Ae, Be)
    print()
    print("sol", curr_sol)
    print("eroare relativa intrare A", (A-Ae)/A)
    print("eroare relativa intrare B", (B-Be)/Be)
    print("eroare relativa iesire", (curr_sol-sol)/sol)

solve(A, Bp)
solve(Ap, B)

[1. 1. 1. 1.]

sol [  9.2 -12.6   4.5  -1.1]
eroare relativa intrare A [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
eroare relativa intrare B [-0.00311526  0.00436681 -0.00302115  0.00323625]
eroare relativa iesire [  8.2 -13.6   3.5  -2.1]

sol [-81. 137. -34.  22.]
eroare relativa intrare A [[ 0.          0.         -0.0125     -0.02857143]
 [-0.01142857 -0.008       0.          0.        ]
 [ 0.          0.00333333  0.011       0.        ]
 [ 0.00142857  0.002       0.          0.002     ]]
eroare relativa intrare B [0. 0. 0. 0.]
eroare relativa iesire [-82. 136. -35.  21.]


O perturbare mica in valorile membrului stang, sau ale membrului drept, cauzeaza o perturbare mare in rezultat.

In [4]:
print(cond(A, lambda a: np.sqrt(np.sum(a**2))))

3009.578708058694


Numarul de conditionare pentru matricea $A$ este foarte mare => matricea este prost conditionata.

# 2

$$
\begin{aligned}
H_n&=h_{ij} \\
h_{ij}&=\frac{1}{i+j-1},i,j=\overline{1,n} \\
\end{aligned}
$$

In [5]:
def hilbert(n):
    return np.array([
        [
            1 / (float(i) + float(j) + 1)
            for j in range(1, n+1)
        ]
        for i in range(1, n+1)
    ])

def norm(a):
    return np.sqrt(np.sum(a**2))

for n in range(10, 15+1):
    H = hilbert(n)
    print(n, cond(H, norm))

10 243627831396782.78
11 8065027222046120.0
12 4.659772368801568e+17
13 1.5361567226069654e+17
14 2.889796530398128e+17
15 1.8450275190664804e+18


valori foarte mari => prost conditionat

# 3 a

$$
\begin{aligned}
t_k&=-1+k\frac{2}{n} \\
n&=\overline{10,15} \\
\end{aligned}
$$

In [12]:
# chebyshev norm is max()

In [6]:
def vandermonde(t, n):
    assert isinstance(t, np.ndarray)

    return (
        np.repeat(np.expand_dims(t, 1), n, 1)
        **
        np.repeat(np.expand_dims(np.arange(n), 0), len(t), 0)
    )


for n in range(10, 15+1):
    Tk = np.array([-1 + k*(2/n) for k in range(1, n+1)])
    V = vandermonde(Tk, n)
    print(n, cond(V, np.max))

10 813.8020833333593
11 2543.999849106264
12 6998.399999998299
13 17585.26329748235
14 49585.74008239154
15 146213.32021828683


# 3 b

$$
t_k=\frac{1}{k}
$$

In [7]:
for n in range(10, 15+1):
    Tk = np.array([1/k for k in range(1, n+1)])
    V = vandermonde(Tk, n)
    print(n, cond(V, np.max))

10 16935359821.947939
11 663042996051.1141
12 25541459318565.074
13 854792734346313.1
14 2656457500257101.5
15 4.618013664367127e+16


# 4

$$
(\text{cond}f(x))=\left|\frac{xf'(x)}{f(x)}\right|
$$